"""Optional PostgreSQL backend sharing the existing store's contract checks.

The SQL in SQLiteDecisionEventStore is deliberately a small, portable subset.
This adapter translates only its parameter markers and write transaction entry;
it is not a general SQLite compatibility layer. Writers are serialized with a
database-scoped advisory lock to preserve the existing read-then-write CAS rules.
"""
from __future__ import annotations

from datetime import UTC, datetime
from threading import RLock

from app.store.sqlite import SQLiteDecisionEventStore, StoreError, _MIGRATION_DIR


_WRITE_LOCK = 1347569997


class _Result:
    def __init__(self, rows):
        self.rows = rows

    def fetchone(self):
        return self.rows.pop(0) if self.rows else None

    def fetchall(self):
        rows, self.rows = self.rows, []
        return rows


class _Connection:
    def __init__(self, connection):
        self.raw = connection

    def execute(self, statement, parameters=None):
        try:
            if statement.strip().upper() == "BEGIN IMMEDIATE":
                # BEGIN is outside the inherited methods' try blocks. Undo it
                # here if acquiring the lock times out, keeping the store usable.
                try:
                    with self.raw.cursor() as cursor:
                        cursor.execute("BEGIN")
                        cursor.execute("SELECT pg_advisory_xact_lock(%s)", (_WRITE_LOCK,))
                except Exception:
                    self.raw.rollback()
                    raise
                return _Result([])
            with self.raw.cursor() as cursor:
                cursor.execute(statement.replace("?", "%s"), parameters)
                return _Result(cursor.fetchall() if cursor.description else [])
        except Exception:
            # Driver diagnostics may contain a DSN or user-supplied values.
            raise StoreError("PostgreSQL persistence operation failed") from None

    def close(self):
        self.raw.close()


class PostgresDecisionEventStore(SQLiteDecisionEventStore):
    """Explicit PostgreSQL DSN; never falls back to a different database.

    Install the ``postgres`` extra. Use a dedicated database/schema and a
    restricted role. This conservative backend serializes write transactions;
    it does not claim the throughput of a pooled PostgreSQL architecture.
    """

    def __init__(self, database_url: str):
        if not isinstance(database_url, str) or not database_url.strip():
            raise ValueError("PostgreSQL connection configuration is required")
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError:
            raise StoreError("PostgreSQL requires the postgres optional dependency") from None
        self._lock = RLock()
        try:
            connection = psycopg.connect(database_url, autocommit=True, row_factory=dict_row,
                                         connect_timeout=5)
        except Exception:
            raise StoreError("PostgreSQL connection failed") from None
        self._connection = _Connection(connection)
        try:
            self._connection.execute("SET statement_timeout = '15s'")
            self._connection.execute("SET lock_timeout = '5s'")
            # The first read after waiting for another writer must observe its
            # commit, even when a server role defaults to repeatable read.
            self._connection.execute("SET default_transaction_isolation = 'read committed'")
            self._run_migrations()
        except Exception:
            self._connection.close()
            raise

    def _run_migrations(self):
        # DDL and version registration commit together; concurrent constructors
        # acquire the same lock before checking which versions are installed.
        self._connection.execute("BEGIN IMMEDIATE")
        try:
            self._connection.execute("CREATE TABLE IF NOT EXISTS schema_migrations "
                                     "(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)")
            applied = {row["version"] for row in self._connection.execute(
                "SELECT version FROM schema_migrations").fetchall()}
            for path in sorted(_MIGRATION_DIR.glob("*.sql")):
                version = int(path.name.split("_", 1)[0])
                if version in applied:
                    continue
                script = path.read_text(encoding="utf-8").replace(
                    "INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                self._connection.execute(script)
                self._connection.execute("INSERT INTO schema_migrations(version, applied_at) VALUES (?, ?)",
                                         (version, datetime.now(UTC).isoformat()))
            self._connection.execute("COMMIT")
        except Exception:
            self._connection.execute("ROLLBACK")
            raise


__all__ = ["PostgresDecisionEventStore"]
